'use client';
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type AdminStats = { users: number; courses: number; questions: number; attempts: number; pending: number };
type AdminCourse = { id: string; code: string; title: string; description: string; questionCount: number };
type AdminRequest = { request: { id: string; requestText: string; status: string; createdAt: string; userId: string }; user: { username: string } };
const adminNav = [{ key: "overview", label: "Dashboard", icon: "▦" }, { key: "courses", label: "Courses", icon: "▤" }, { key: "banks", label: "Question Banks", icon: "≡" }, { key: "modules", label: "Manage Modules", icon: "✦" }, { key: "users", label: "Users", icon: "◯" }, { key: "requests", label: "Requested Courses", icon: "＋" }, { key: "leaderboard", label: "Leaderboard", icon: "↗" }];
const prompt = `Convert the attached PDF question bank into CSV using exactly these columns:\nquestion,optionA,optionB,optionC,optionD,correctAnswer,explanation\n\nExtract every question exactly as written. Put the four answer options into optionA, optionB, optionC and optionD. Put the correct option letter (A, B, C or D) in correctAnswer. In the explanation column, write one short, clear sentence explaining why the correct answer is correct. Do not create, rewrite, summarize or invent questions or answers. Return only valid CSV data with the header row. Properly escape commas, quotation marks and line breaks so the CSV can be imported correctly.`;

async function adminFetch(url: string, options?: RequestInit) {
  const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(options?.headers ?? {}) } });
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("application/json")) throw new Error(response.status === 401 ? "UNAUTHORIZED" : "The server returned an unexpected response. Please try again.");
  const data = await response.json();
  if (response.status === 401) throw new Error("UNAUTHORIZED");
  return { ok: response.ok, status: response.status, data };
}

export default function AdminDashboardPage() { const router = useRouter(); const [section, setSection] = useState("overview"); const [sidebarOpen, setSidebarOpen] = useState(false); const [stats, setStats] = useState<AdminStats>({ users: 0, courses: 0, questions: 0, attempts: 0, pending: 0 }); const [courses, setCourses] = useState<AdminCourse[]>([]); const [requests, setRequests] = useState<AdminRequest[]>([]); const [recentUsers, setRecentUsers] = useState<{ username: string; matriculationNumber: string; createdAt: string }[]>([]); const [toast, setToast] = useState(""); const [courseForm, setCourseForm] = useState({ code: "", title: "", description: "" }); const [importForm, setImportForm] = useState({ courseId: "", year: "2026", csv: "" }); const [users, setUsers] = useState<{ username: string; matriculationNumber: string; phoneNumber: string | null; createdAt: string; isActive: boolean }[]>([]); const [userSearch, setUserSearch] = useState(""); const [leaderboard, setLeaderboard] = useState<{ username: string; average: number; attempts: number }[]>([]);
  async function load() { const res = await adminFetch("/api/admin/dashboard"); if (res.ok) { setStats(res.data.stats); setRecentUsers(res.data.recentUsers); setRequests(res.data.requests); } const cr = await adminFetch("/api/admin/courses"); if (cr.ok) setCourses(cr.data.courses); }
  useEffect(() => { load().catch(() => router.push("/admin/login")); }, [router]);
  useEffect(() => { if (section === "users") adminFetch(`/api/admin/users?q=${encodeURIComponent(userSearch)}`).then((res) => { if (res.ok) setUsers(res.data.users || []); }).catch(() => undefined); if (section === "leaderboard") adminFetch("/api/admin/leaderboard").then((res) => { if (res.ok) setLeaderboard(res.data.leaderboard || []); }).catch(() => undefined); }, [section, userSearch]);
  const pageTitle = useMemo(() => adminNav.find((item) => item.key === section)?.label || "Dashboard", [section]);
  function notify(message: string) { setToast(message); setTimeout(() => setToast(""), 3200); }
  async function createCourse() { const res = await adminFetch("/api/admin/courses", { method: "POST", body: JSON.stringify(courseForm) }); if (!res.ok) return notify(res.data.error || "Could not create course."); setCourseForm({ code: "", title: "", description: "" }); notify("Course created successfully."); load(); }
  async function importCsv() { const res = await adminFetch("/api/admin/import", { method: "POST", body: JSON.stringify(importForm) }); if (!res.ok) return notify(res.data.error || "Question import failed."); setImportForm({ ...importForm, csv: "" }); notify(`${res.data.imported} questions imported successfully${res.data.invalid ? ` · ${res.data.invalid} invalid rows skipped` : ""}.`); load(); }
  async function updateRequest(id: string, status: string) { const res = await adminFetch("/api/admin/requests", { method: "PATCH", body: JSON.stringify({ id, status }) }); if (res.ok) { notify(`Request ${status.toLowerCase()}.`); load(); } }
  function logout() { adminFetch("/api/auth/logout", { method: "POST" }).catch(() => undefined).finally(() => router.push("/admin/login")); }
  return <div className="admin-shell"><aside className={`admin-sidebar ${sidebarOpen ? "open" : ""}`}><div className="admin-brand"><span className="brand-mark">N</span><div><strong>NounStudyHub</strong><small>Admin console</small></div><button className="admin-sidebar-close" onClick={() => setSidebarOpen(false)} aria-label="Close menu">×</button></div><div className="admin-side-label">WORKSPACE</div>{adminNav.map((item) => <button key={item.key} className={section === item.key ? "active" : ""} onClick={() => setSection(item.key)}><span>{item.icon}</span>{item.label}{item.key === "requests" && stats.pending > 0 && <b>{stats.pending}</b>}</button>)}<div className="admin-sidebar-bottom"><button onClick={() => notify("Settings are coming soon.")}><span>⚙</span>Settings</button><button onClick={logout}><span>↗</span>Log out</button></div></aside><main className="admin-main"><header className="admin-header"><button className="admin-menu-button" onClick={() => setSidebarOpen(true)} aria-label="Open menu">☰</button><div><span className="admin-breadcrumb">ADMIN / {pageTitle.toUpperCase()}</span><h1>{pageTitle}</h1></div><div className="admin-header-actions"><button className="admin-bell">♧{stats.pending > 0 && <i/>}</button><span className="admin-avatar">A</span><span className="admin-user-label">Administrator</span></div></header>{toast && <div className="admin-toast">✓ {toast}</div>}<div className="admin-content">{section === "overview" && <Overview stats={stats} recentUsers={recentUsers} requests={requests} setSection={setSection}/>} {section === "courses" && <CoursesSection courses={courses} form={courseForm} setForm={setCourseForm} onCreate={createCourse} onModules={(id) => router.push(`/admin/modules/${id}`)}/>} {section === "banks" && <BanksSection courses={courses} form={importForm} setForm={setImportForm} onImport={importCsv} prompt={prompt}/>} {section === "modules" && <ModulesSection courses={courses} onModules={(id) => router.push(`/admin/modules/${id}`)}/>} {section === "users" && <UsersSection users={users} query={userSearch} setQuery={setUserSearch}/>} {section === "requests" && <RequestsSection requests={requests} onUpdate={updateRequest}/>} {section === "leaderboard" && <AdminLeaderboard rows={leaderboard}/>}</div></main>{sidebarOpen && <div className="admin-backdrop" onClick={() => setSidebarOpen(false)} />}</div>; }

function Overview({ stats, recentUsers, requests, setSection }: { stats: AdminStats; recentUsers: { username: string; matriculationNumber: string; createdAt: string }[]; requests: AdminRequest[]; setSection: (s: string) => void }) { const cards = [["Total users", stats.users, "↗ Community growth", "green"], ["Total courses", stats.courses, "Available to students", "blue"], ["Total questions", stats.questions, "Across all banks", "purple"], ["Mock attempts", stats.attempts, "Practice sessions", "orange"]]; return <><div className="admin-welcome"><div><span className="admin-kicker">TUESDAY, SEPTEMBER 9, 2026</span><h2>Good morning, administrator.</h2><p>Here’s what’s happening across NounStudyHub today.</p></div><button onClick={() => setSection("courses")}>+ Add course</button></div><div className="admin-stat-grid">{cards.map(([label, value, note, tone]) => <div className="admin-stat" key={label}><span className={`admin-stat-icon ${tone}`}>{tone === "green" ? "◯" : tone === "blue" ? "▤" : tone === "purple" ? "≡" : "↗"}</span><small>{label}</small><strong>{value}</strong><p>{note}</p></div>)}</div><div className="admin-overview-grid"><div className="admin-panel"><div className="admin-panel-head"><div><h3>Recently registered</h3><p>New students joining the platform.</p></div><button onClick={() => setSection("users")}>View all →</button></div>{recentUsers.length ? recentUsers.map((user) => <div className="admin-list-row" key={user.username}><span className="admin-mini-avatar">{user.username[0]}</span><div><strong>{user.username}</strong><small>{user.matriculationNumber}</small></div><time>{new Date(user.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })}</time></div>) : <div className="admin-empty">No students registered yet.</div>}</div><div className="admin-panel"><div className="admin-panel-head"><div><h3>Pending requests</h3><p>Course ideas from students.</p></div><button onClick={() => setSection("requests")}>View all →</button></div>{requests.slice(0, 4).map((item) => <div className="admin-request-row" key={item.request.id}><div><strong>{item.request.requestText}</strong><small>by {item.user.username}</small></div><span className={`admin-status ${item.request.status.toLowerCase()}`}>{item.request.status}</span></div>)}{!requests.length && <div className="admin-empty">No course requests yet.</div>}</div></div><div className="admin-callout"><span>✦</span><div><strong>Question banks are the heart of the platform.</strong><p>Keep course content fresh by importing past questions year by year. Existing years can receive additional questions without creating duplicates.</p></div><button onClick={() => setSection("banks")}>Manage question banks →</button></div></>; }
function CoursesSection({ courses, form, setForm, onCreate, onModules }: { courses: AdminCourse[]; form: { code: string; title: string; description: string }; setForm: (v: { code: string; title: string; description: string }) => void; onCreate: () => void; onModules: (id: string) => void }) { return <><div className="admin-section-intro"><div><h2>Course library</h2><p>Add course-first learning spaces that students can discover instantly.</p></div><button onClick={onCreate}>Create course <span>→</span></button></div><div className="admin-create-form"><div><label>Course code<input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="ECO231"/></label><label>Course title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Micro Economic Theory I"/></label><label>Description<input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Short course description"/></label></div></div><div className="admin-course-table"><div className="admin-table-head"><span>Course</span><span>Questions</span><span>Content</span><span>Actions</span></div>{courses.map((course) => <div className="admin-table-row" key={course.id}><div><span className="admin-course-mark">{course.code[0]}</span><span><strong>{course.code}</strong><small>{course.title}</small></span></div><span>{course.questionCount}</span><span><span className="admin-content-pill">4 modules</span></span><div><button onClick={() => onModules(course.id)}>Manage modules</button><button>View</button></div></div>)}</div></>; }
function BanksSection({ courses, form, setForm, onImport, prompt }: { courses: AdminCourse[]; form: { courseId: string; year: string; csv: string }; setForm: (v: { courseId: string; year: string; csv: string }) => void; onImport: () => void; prompt: string }) { const [copied, setCopied] = useState(false); return <><div className="admin-section-intro"><div><h2>Question banks</h2><p>Import valid CSV question sets, year by year. Existing years append safely.</p></div><button onClick={() => document.getElementById("csv-import")?.scrollIntoView()}>+ Add questions</button></div><div className="bank-cards">{courses.map((course) => <div className="bank-card" key={course.id}><span className="admin-course-mark">{course.code[0]}</span><div><strong>{course.code}</strong><small>{course.title}</small></div><b>{course.questionCount} questions</b><span className="bank-years">2023 · 2024 · 2025 · 2026</span></div>)}</div><div id="csv-import" className="import-layout"><div className="admin-panel import-panel"><div className="admin-panel-head"><div><h3>Import CSV questions</h3><p>Validate first, then append to an existing or new year.</p></div><span className="step-badge">01 / 02</span></div><label>Course<select value={form.courseId} onChange={(e) => setForm({ ...form, courseId: e.target.value })}><option value="">Select a course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code} · {course.title}</option>)}</select></label><label>Question-bank year<input type="number" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value })}/></label><label>CSV content<textarea value={form.csv} onChange={(e) => setForm({ ...form, csv: e.target.value })} rows={8} placeholder="question,optionA,optionB,optionC,optionD,correctAnswer,explanation&#10;…"/></label><button className="admin-primary-button" onClick={onImport}>Validate & import questions <span>→</span></button></div><div className="admin-panel prompt-panel"><div className="admin-panel-head"><div><h3>PDF → CSV prompt</h3><p>Copy this into your preferred AI tool.</p></div><span>AI helper</span></div><pre>{prompt}</pre><button onClick={() => { navigator.clipboard?.writeText(prompt); setCopied(true); setTimeout(() => setCopied(false), 2000); }}>{copied ? "✓ Copied" : "Copy AI prompt"}</button></div></div></>; }
function ModulesSection({ courses, onModules }: { courses: AdminCourse[]; onModules: (id: string) => void }) { return <><div className="admin-section-intro"><div><h2>Manage modules</h2><p>Open a dedicated course workspace to write summaries and organise modules.</p></div></div><div className="module-admin-cards">{courses.map((course) => <div key={course.id} className="module-admin-card"><span className="admin-course-mark">{course.code[0]}</span><div><strong>{course.code}</strong><small>{course.title}</small></div><span className="module-count">4 modules</span><button onClick={() => onModules(course.id)}>Open workspace →</button></div>)}</div></>; }
function UsersSection({ users, query, setQuery }: { users: { username: string; matriculationNumber: string; phoneNumber: string | null; createdAt: string; isActive: boolean }[]; query: string; setQuery: (v: string) => void }) { return <><div className="admin-section-intro"><div><h2>Students</h2><p>Search, review and understand your student community.</p></div><label className="admin-search">⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search username"/></label></div><div className="admin-panel admin-user-table"><div className="admin-table-head"><span>Student</span><span>Matriculation</span><span>Phone</span><span>Joined</span><span>Status</span></div>{users.map((user) => <div className="admin-table-row" key={user.username}><div><span className="admin-mini-avatar">{user.username[0]}</span><span><strong>{user.username}</strong><small>Student</small></span></div><span>{user.matriculationNumber}</span><span>{user.phoneNumber || "—"}</span><span>{new Date(user.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</span><span className="admin-status approved">{user.isActive ? "Active" : "Suspended"}</span></div>)}</div></>; }
function RequestsSection({ requests, onUpdate }: { requests: AdminRequest[]; onUpdate: (id: string, status: string) => void }) { return <><div className="admin-section-intro"><div><h2>Requested courses</h2><p>Listen to what students want to study next.</p></div></div><div className="admin-panel admin-requests-table">{requests.map((item) => <div className="admin-request-full" key={item.request.id}><div><strong>{item.request.requestText}</strong><small>{item.user.username} · {new Date(item.request.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</small></div><span className={`admin-status ${item.request.status.toLowerCase()}`}>{item.request.status}</span><div className="request-actions"><button onClick={() => onUpdate(item.request.id, "Approved")}>Approve</button><button onClick={() => onUpdate(item.request.id, "Declined")}>Decline</button></div></div>)}{!requests.length && <div className="admin-empty">No course requests to review.</div>}</div></>; }
function AdminLeaderboard({ rows }: { rows: { username: string; average: number; attempts: number }[] }) { return <><div className="admin-section-intro"><div><h2>Platform leaderboard</h2><p>Best-performing students based on a meaningful history of completed mocks.</p></div><span className="admin-note-pill">Minimum 2 mocks</span></div><div className="admin-panel admin-leader-table"><div className="admin-table-head"><span>Rank</span><span>Student</span><span>Average performance</span><span>Completed mocks</span></div>{rows.map((row, i) => <div className="admin-table-row" key={row.username}><strong className="admin-rank">{String(i + 1).padStart(2, "0")}</strong><div><span className="admin-mini-avatar">{row.username[0]}</span><strong>{row.username}</strong></div><span className="admin-average">{row.average}%</span><span>{row.attempts}</span></div>)}{!rows.length && <div className="admin-empty">Leaderboard is forming as students complete more mocks.</div>}</div></>; }
